#!/bin/bash

export BINDIR=/usr/local/bin

export BITSDIR=/home/ubuntu/download

#Pivotal network 
export APIREFRESHTOKEN="<insert-refresh-token-here>"

# VMware Download Account
export VMWUSER='<username>'
export VMWPASS='<password>'

# CLI Tools version
export PIVNETRELEASE=1.0.3
export BOSHRELEASE=5.4.0
export HELMRELEASE=2.13.1
export OMRELEASE=4.6.0

# VMware SW Releases [ProductGroup]
export OVFTOOLPG=OVFTOOL430
export NSXTPG=NSX-T-251
export VRLIPG=VRLI-460
export VROPSPG=VROPS-670

# VMware Tanzu SW Releases
export OPSMANRELEASE=2.4.6
export PKSRELEASE=1.3.3
export STEMCELLRELEASE=3586.36
export HARBORRELEASE=1.7.3
export STEMCELLXENIALRELEASE=170.15
export BUILDSERVICERELEASE=0.1.0
export BBRRELEASE=1.7.2